apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-advisor-agent.fullname" . }}
  labels:
    {{- include "kube-advisor-agent.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
