apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-advisor-agent.fullname" . }}
automountServiceAccountToken: true

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-advisor-agent.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods", "nodes", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["kyverno.io"]
  resources: ["clusterpolicies"]
  verbs: ["get", "list", "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-advisor-agent.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-advisor-agent.fullname" . }} 
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kube-advisor-agent.fullname" . }}
  apiGroup: rbac.authorization.k8s.io