apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-advisor-agent.fullname" . }}-certificates
  labels:
    {{- include "kube-advisor-agent.labels" . | nindent 4 }}
data:
  ca.pem: {{ required "CA certificate needs to be provided at certificates.ca!" .Values.certificates.ca }}
  cert.pem: {{ required "TLS client certificate needs to be provided certificates.cert!" .Values.certificates.cert }}
  private.key: {{ required "TLS client certificate key needs to be provided at certificates.key!" .Values.certificates.key }}