# -- Internal settings used with `helm template` to generate install manifest
# @ignored
templating:
  enabled: false
  debug: false
  version: ~

groups:

  # -- Install CRDs in group `kyverno.io`
  # -- This field can be overwritten by setting crds.labels in the parent chart
  kyverno:
    cleanuppolicies: true
    clustercleanuppolicies: true
    clusterpolicies: true
    globalcontextentries: true
    policies: true
    policyexceptions: true
    updaterequests: true

  # -- Install CRDs in group `reports.kyverno.io`
  # -- This field can be overwritten by setting crds.labels in the parent chart
  reports:
    clusterephemeralreports: true
    ephemeralreports: true

  # -- Install CRDs in group `wgpolicyk8s.io`
  # -- This field can be overwritten by setting crds.labels in the parent chart
  wgpolicyk8s:
    clusterpolicyreports: true
    policyreports: true

# -- Additional CRDs annotations
# -- This field can be overwritten by setting crds.annotations in the parent chart
annotations: {}
  # argocd.argoproj.io/sync-options: Replace=true
  # strategy.spinnaker.io/replace: 'true'

# -- Additional CRDs labels
# -- This field can be overwritten by setting crds.labels in the parent chart
customLabels: {}


crds:

  # -- Whether to have Helm install the Kyverno CRDs, if the CRDs are not installed by Helm, they must be added before policies can be created
  install: true

  groups:

    # -- Install CRDs in group `kyverno.io`
    kyverno:
      cleanuppolicies: true
      clustercleanuppolicies: true
      clusterpolicies: true
      globalcontextentries: true
      policies: true
      policyexceptions: true
      updaterequests: true

    # -- Install CRDs in group `reports.kyverno.io`
    reports:
      clusterephemeralreports: true
      ephemeralreports: true

    # -- Install CRDs in group `wgpolicyk8s.io`
    wgpolicyk8s:
      clusterpolicyreports: true
      policyreports: true

  # -- Additional CRDs annotations
  annotations: {}
    # argocd.argoproj.io/sync-options: Replace=true
    # strategy.spinnaker.io/replace: 'true'

  # -- Additional CRDs labels
  customLabels: {}

  migration:

    # -- Enable CRDs migration using helm post upgrade hook
    enabled: true

    # -- Resources to migrate
    resources:
      - cleanuppolicies.kyverno.io
      - clustercleanuppolicies.kyverno.io
      - clusterpolicies.kyverno.io
      - globalcontextentries.kyverno.io
      - policies.kyverno.io
      - policyexceptions.kyverno.io
      - updaterequests.kyverno.io

    image:
      # -- (string) Image registry
      registry: ghcr.io
      # -- (string) Image repository
      repository: kyverno/kyverno-cli
      # -- (string) Image tag
      # Defaults to appVersion in Chart.yaml if omitted
      tag: ~
      # -- (string) Image pull policy
      pullPolicy: IfNotPresent

    # -- Image pull secrets
    imagePullSecrets: []
    # - name: secretName

    # -- Security context for the pod
    podSecurityContext: {}

    # -- Node labels for pod assignment
    nodeSelector: {}

    # -- List of node taints to tolerate
    tolerations: []

    # -- Pod anti affinity constraints.
    podAntiAffinity: {}

    # -- Pod affinity constraints.
    podAffinity: {}

    # -- Pod labels.
    podLabels: {}

    # -- Pod annotations.
    podAnnotations: {}

    # -- Node affinity constraints.
    nodeAffinity: {}

    # -- Security context for the hook containers
    securityContext:
      runAsUser: 65534
      runAsGroup: 65534
      runAsNonRoot: true
      privileged: false
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault